# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFLtBN4bqJMu0SfR6_Ek46enkYZpimOS
"""

pip install gTTS moviepy gradio torch diffusers

# ✅ Step 2: Import libraries
import torch
from diffusers import StableDiffusionPipeline
from gtts import gTTS
import os
import gradio as gr
import moviepy.editor as mp

# ✅ Step 3: Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"

# ✅ Step 4: Load AI Models
pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5").to(device)

def generate_script(user_input):
    """Generates a script based on user input."""
    return f"Generated Script: {user_input}"

def generate_images(script):
    """Generates an image from the script description."""
    image = pipe(script).images[0]
    image_path = "generated_scene.png"
    image.save(image_path)
    return image_path

def generate_voice(script):
    """Converts script to speech using Google TTS."""
    audio_path = "output.wav"
    tts = gTTS(text=script, lang="en")
    tts.save(audio_path)
    return audio_path

def create_video(image_path, audio_path):
    """Creates a simple video with image and audio."""
    image_clip = mp.ImageClip(image_path).set_duration(20)  # 5-second video
    audio_clip = mp.AudioFileClip(audio_path)
    video_clip = image_clip.set_audio(audio_clip)
    output_video = "generated_video.mp4"
    video_clip.write_videofile(output_video, codec="libx264", fps=24)
    return output_video

def generate_movie(script):
    """Main function to generate movie from script."""
    image_path = generate_images(script)
    audio_path = generate_voice(script)
    video_path = create_video(image_path, audio_path)
    return script, image_path, audio_path, video_path

# ✅ Step 5: Create Gradio UI
iface = gr.Interface(
    fn=generate_movie,
    inputs=[gr.Textbox(label="Enter Script")],
    outputs=[
        gr.Textbox(label="Generated Script"),
        gr.Image(label="Generated Image"),
        gr.Audio(label="Generated Voice"),
        gr.Video(label="Generated Video")
    ],
    title="🎬 AI Movie Generator",
    description="Enter a script, and AI will generate a movie!",
)

# ✅ Step 6: Run UI
iface.launch(share=True)